[username]
style_user = 'white bold'
style_root = 'black bold'
format = 'user: [$user]($style) '
disabled = false
show_always = true

[python]
pyenv_version_name = true
detect_extensions = ["py", "ipynb"]
detect_files = [
	".python-version",
	"pyproject.toml",
	"requirements.txt",
	"setup.py",
]

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[hostname]
ssh_only = true
format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '

# [localip]
# ssh_only = false
# format = '@[$localipv4](bold red) '
# disabled = false

[terraform]
format = 'via [$symbol$version $workspace]($style) '
